// <auto-generated />
using System;
using BlueLagoon.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250709082154_Seed Amenity data")]
    partial class SeedAmenitydata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlueLagoon.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "xx",
                            Name = "Pool",
                            VillaId = 13
                        },
                        new
                        {
                            Id = 2,
                            Description = "De",
                            Name = "Jaquse",
                            VillaId = 13
                        },
                        new
                        {
                            Id = 3,
                            Description = "De",
                            Name = "Balcony",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "De",
                            Name = "Beach View",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "De",
                            Name = "Terrace",
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("BlueLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Near the beach",
                            ImageUrl = "",
                            Name = "Deluxe Villa",
                            Occupancy = 4,
                            Price = 10000.0,
                            Sqft = 400,
                            Updated_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Created_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pool View",
                            ImageUrl = "",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 30000.0,
                            Sqft = 550,
                            Updated_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Created_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kind Size Bed",
                            ImageUrl = "",
                            Name = "Luxury Pool Villa",
                            Occupancy = 10,
                            Price = 80000.0,
                            Sqft = 1050,
                            Updated_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BlueLagoon.Domain.Entities.VillaSuite", b =>
                {
                    b.Property<int>("VillaSuitId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaSuitId");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaSuites");

                    b.HasData(
                        new
                        {
                            VillaSuitId = 101,
                            VillaId = 1
                        },
                        new
                        {
                            VillaSuitId = 102,
                            VillaId = 1
                        },
                        new
                        {
                            VillaSuitId = 103,
                            VillaId = 1
                        },
                        new
                        {
                            VillaSuitId = 201,
                            VillaId = 2
                        },
                        new
                        {
                            VillaSuitId = 202,
                            VillaId = 2
                        },
                        new
                        {
                            VillaSuitId = 203,
                            VillaId = 2
                        },
                        new
                        {
                            VillaSuitId = 301,
                            VillaId = 3
                        },
                        new
                        {
                            VillaSuitId = 302,
                            VillaId = 3
                        },
                        new
                        {
                            VillaSuitId = 303,
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("BlueLagoon.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("BlueLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("BlueLagoon.Domain.Entities.VillaSuite", b =>
                {
                    b.HasOne("BlueLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
